import { palette } from './palette'

export const baseTheme = {
  light: {
    background: palette.neutral[50],
    foreground: palette.neutral[950],
    card: palette.neutral[50],
    cardForeground: palette.neutral[950],
    popover: palette.neutral[50],
    popoverForeground: palette.neutral[950],
    primary: palette.neutral[950],
    primaryForeground: palette.neutral[50],
    secondary: palette.neutral[950],
    secondaryForeground: palette.neutral[50],
    muted: palette.neutral[50],
    mutedForeground: palette.neutral[950],
    accent: palette.blue[50],
    accentForeground: palette.blue[950],
    destructive: palette.red[500],
    destructiveForeground: palette.red[50],
    border: palette.neutral[200],
    input: palette.neutral[200],
    ring: palette.neutral[950],
    radius: '0.5rem',
    chart1: palette.blue[50],
    chart2: palette.blue[100],
    chart3: palette.blue[200],
    chart4: palette.blue[300],
    chart5: palette.blue[400],
  },
  dark: {
    background: palette.neutral[950],
    foreground: palette.neutral[50],
    card: palette.neutral[950],
    cardForeground: palette.neutral[50],
    popover: palette.neutral[950],
    popoverForeground: palette.neutral[50],
    primary: palette.neutral[50],
    primaryForeground: palette.neutral[950],
    secondary: palette.neutral[50],
    secondaryForeground: palette.neutral[950],
    muted: palette.neutral[950],
    mutedForeground: palette.neutral[50],
    accent: palette.blue[950],
    accentForeground: palette.blue[50],
    destructive: palette.red[500],
    destructiveForeground: palette.red[50],
    border: palette.neutral[800],
    input: palette.neutral[800],
    ring: palette.neutral[950],
    chart1: palette.blue[50],
    chart2: palette.blue[100],
    chart3: palette.blue[200],
    chart4: palette.blue[300],
    chart5: palette.blue[400],
  },
}
