#!/bin/sh
# Start a single-node Garage daemon and provision a key + the system buckets.
# Shared by the dev, test and production entrypoints. Idempotent so it survives
# the persisted data volume.
#
# Credentials are auto-generated by default (every environment): Garage mints a
# key on first boot (or an existing same-named key is reused); it is read back
# and persisted to
# ${GARAGE_DATA_ROOT}/.lombok-builtin-key as EMBEDDED_S3_ACCESS_KEY_ID /
# EMBEDDED_S3_SECRET_ACCESS_KEY, and reused on later boots. The entrypoint
# sources that file to hand the creds to the API. (A fixed key can still be
# imported by supplying GARAGE_S3_ACCESS_KEY_ID + GARAGE_S3_SECRET_KEY.)
#
# Inputs (env):
#   GARAGE_CONFIG_FILE             path to garage.toml (default /etc/garage.toml)
#   APP_USER                       user owning the data dirs / running the daemon (default bun)
#   GARAGE_S3_ACCESS_KEY_ID        fixed access key to import (omit to auto-generate)
#   GARAGE_S3_SECRET_KEY           fixed secret for that key
#   GARAGE_S3_KEY_NAME             key label (default lombok)
#   GARAGE_SERVER_STORAGE_BUCKET   server-storage bucket name (default server-storage)
#   GARAGE_PROVISIONS_BUCKET       builtin provision bucket name (default provisions)
#   GARAGE_UPLOADS_BUCKET          staged-uploads bucket name (default uploads)
#   GARAGE_EXTRA_BUCKETS           space-separated extra buckets (created+granted+CORS)
#   GARAGE_S3_ENDPOINT             S3 endpoint for the CORS step (default http://127.0.0.1:9000)
#   GARAGE_KEY_CREATE_BUCKET       set to 1 to also grant the key createBucket (e2e harness)
#   GARAGE_LOG_LEVEL               daemon+CLI log verbosity (RUST_LOG; default "error")
set -e

export GARAGE_CONFIG_FILE="${GARAGE_CONFIG_FILE:-/etc/garage.toml}"
# Quiet by default so Garage doesn't flood dev/e2e output; raise to info/debug
# via GARAGE_LOG_LEVEL when diagnosing. Applies to the daemon and the CLI calls.
export RUST_LOG="${GARAGE_LOG_LEVEL:-error}"
APP_USER="${APP_USER:-bun}"
GARAGE_S3_KEY_NAME="${GARAGE_S3_KEY_NAME:-lombok}"
GARAGE_S3_ENDPOINT="${GARAGE_S3_ENDPOINT:-http://127.0.0.1:9000}"
# Production default: loopback-only (all S3 access goes through nginx). Dev/e2e
# entrypoints override to "[::]:9000" so the host can reach Garage directly.
GARAGE_API_BIND_ADDR="${GARAGE_API_BIND_ADDR:-127.0.0.1:9000}"
GARAGE_DATA_ROOT='/var/lib/garage'
LAYOUT_SENTINEL="${GARAGE_DATA_ROOT}/.lombok-layout-applied"

mkdir -p "$GARAGE_DATA_ROOT"
chown -R "$APP_USER":"$APP_USER" "$GARAGE_DATA_ROOT"

# Render a runtime config with the per-environment S3 bind address substituted
# in, and point the daemon + CLI at it. (The shipped /etc/garage.toml carries a
# {{GARAGE_API_BIND_ADDR}} placeholder.)
GARAGE_RUNTIME_CONFIG="${GARAGE_DATA_ROOT}/garage.runtime.toml"
sed "s|{{GARAGE_API_BIND_ADDR}}|${GARAGE_API_BIND_ADDR}|g" \
  "$GARAGE_CONFIG_FILE" > "$GARAGE_RUNTIME_CONFIG"
chown "$APP_USER":"$APP_USER" "$GARAGE_RUNTIME_CONFIG"
export GARAGE_CONFIG_FILE="$GARAGE_RUNTIME_CONFIG"

# Daemon runs as APP_USER (owns the data dirs); CLI runs as the current user and
# reaches the daemon over RPC using the secret in the config file. Record the PID
# so the entrypoint watchdog can adopt this boot instance.
su-exec "$APP_USER" garage server > /dev/stdout 2>&1 &
echo $! > "${GARAGE_DATA_ROOT}/.garage.pid"

echo "Waiting for Garage to be ready..."
until garage status > /dev/null 2>&1; do
  sleep 1
done
echo "Garage daemon is up."

# Cluster layout: assign this lone node a role once, then never again (the
# next apply would be a new version). Sentinel persists on the dev volume.
if [ ! -f "$LAYOUT_SENTINEL" ]; then
  NODE_ID=$(garage node id -q 2>/dev/null | head -1 | cut -d@ -f1)
  garage layout assign -z dc1 -c 1G "$NODE_ID"
  garage layout apply --version 1
  touch "$LAYOUT_SENTINEL"
  echo "Garage cluster layout applied."
fi

# Wait for the node to be ready to serve data after layout.
until garage status > /dev/null 2>&1; do
  sleep 1
done

# Key: either import a fixed dev/test key, or auto-generate + persist one.
KEY_FILE="${GARAGE_DATA_ROOT}/.lombok-builtin-key"
if [ -n "$GARAGE_S3_ACCESS_KEY_ID" ]; then
  # Fixed-credential (dev/e2e) mode — import the supplied key (idempotent).
  if ! garage key info "$GARAGE_S3_ACCESS_KEY_ID" > /dev/null 2>&1; then
    garage key import --yes -n "$GARAGE_S3_KEY_NAME" \
      "$GARAGE_S3_ACCESS_KEY_ID" "$GARAGE_S3_SECRET_KEY"
  fi
else
  # Auto-generate (production) mode — Garage mints the key on first boot; the
  # persisted file makes later boots idempotent.
  if [ -f "$KEY_FILE" ]; then
    . "$KEY_FILE"
  else
    # Reuse an existing same-named key if present (e.g. a prior boot minted one
    # but crashed before persisting); only mint when none exists. Keying off
    # Garage's own state — not just the persisted file — avoids orphaning a
    # second same-named key, which would make `garage key info <name>` ambiguous.
    if ! garage key info "$GARAGE_S3_KEY_NAME" > /dev/null 2>&1; then
      garage key create "$GARAGE_S3_KEY_NAME" > /dev/null
    fi
    _key_info=$(garage key info "$GARAGE_S3_KEY_NAME" --show-secret)
    EMBEDDED_S3_ACCESS_KEY_ID=$(echo "$_key_info" | grep -i '^Key ID:' | sed 's/^[^:]*: *//' | tr -d ' \r')
    EMBEDDED_S3_SECRET_ACCESS_KEY=$(echo "$_key_info" | grep -i '^Secret key:' | sed 's/^[^:]*: *//' | tr -d ' \r')
    # Fail loudly if scraping the id/secret produced nothing (e.g. Garage changed
    # its output format): never persist an empty key file — it would poison every
    # later boot, which sources the file and skips regeneration.
    if [ -z "$EMBEDDED_S3_ACCESS_KEY_ID" ] || [ -z "$EMBEDDED_S3_SECRET_ACCESS_KEY" ]; then
      echo "Error: failed to parse generated Garage key id/secret from 'garage key info'." >&2
      echo "$_key_info" >&2
      exit 1
    fi
    (umask 077; cat > "$KEY_FILE" <<EOF
EMBEDDED_S3_ACCESS_KEY_ID=${EMBEDDED_S3_ACCESS_KEY_ID}
EMBEDDED_S3_SECRET_ACCESS_KEY=${EMBEDDED_S3_SECRET_ACCESS_KEY}
EOF
)
    chown "$APP_USER":"$APP_USER" "$KEY_FILE"
    echo "Garage builtin key generated and persisted."
  fi
  GARAGE_S3_ACCESS_KEY_ID="$EMBEDDED_S3_ACCESS_KEY_ID"
  GARAGE_S3_SECRET_KEY="$EMBEDDED_S3_SECRET_ACCESS_KEY"
  if [ -z "$GARAGE_S3_ACCESS_KEY_ID" ] || [ -z "$GARAGE_S3_SECRET_KEY" ]; then
    echo "Error: builtin Garage credentials are empty (corrupt ${KEY_FILE}?)." >&2
    echo "Remove that file to force regeneration." >&2
    exit 1
  fi
fi

if [ "${GARAGE_KEY_CREATE_BUCKET:-0}" = "1" ]; then
  garage key allow --create-bucket "$GARAGE_S3_ACCESS_KEY_ID"
fi

# The three fixed system buckets. KEEP NAMES IN SYNC with coreConfig defaults in
# packages/api/src/core/config/core.config.ts (s3SystemBuckets).
#   - server-storage : server-side only (app bundles, icons, avatars) — no CORS
#   - provisions     : builtin user-storage provision (browser-direct) — CORS
#   - uploads        : presigned staged uploads (browser-direct) — CORS
GARAGE_SERVER_STORAGE_BUCKET="${GARAGE_SERVER_STORAGE_BUCKET:-server-storage}"
GARAGE_PROVISIONS_BUCKET="${GARAGE_PROVISIONS_BUCKET:-provisions}"
GARAGE_UPLOADS_BUCKET="${GARAGE_UPLOADS_BUCKET:-uploads}"

# Browser-facing buckets get a CORS rule; server-storage does not. Any
# GARAGE_EXTRA_BUCKETS (space-separated, e.g. a dev External-provision demo
# bucket) are created, granted and CORS-enabled too.
CORS_BUCKETS="$GARAGE_PROVISIONS_BUCKET $GARAGE_UPLOADS_BUCKET ${GARAGE_EXTRA_BUCKETS:-}"
ALL_BUCKETS="$GARAGE_SERVER_STORAGE_BUCKET $CORS_BUCKETS"

# Buckets: create + grant the key full access (idempotent).
for _bucket in $ALL_BUCKETS; do
  if ! garage bucket info "$_bucket" > /dev/null 2>&1; then
    garage bucket create "$_bucket"
  fi
  garage bucket allow --read --write --owner "$_bucket" \
    --key "$GARAGE_S3_ACCESS_KEY_ID"
done

# CORS: Garage (unlike MinIO) is not permissive by default. Browser-direct
# presigned uploads/downloads need an explicit rule on each browser-facing bucket.
for _bucket in $CORS_BUCKETS; do
  GARAGE_S3_ACCESS_KEY_ID="$GARAGE_S3_ACCESS_KEY_ID" \
  GARAGE_S3_SECRET_KEY="$GARAGE_S3_SECRET_KEY" \
  GARAGE_S3_BUCKET="$_bucket" \
  GARAGE_S3_ENDPOINT="$GARAGE_S3_ENDPOINT" \
    su-exec "$APP_USER" bun /usr/src/app/packages/api/cmd/garage-set-cors.ts
done

echo "Garage key, buckets and CORS setup complete."
