defaultSemverRangePrefix: ''

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  postcss-loader@*:
    dependencies:
      'tailwindcss': '*'
      'autoprefixer': '*'
  '@storybook/nextjs@*':
    dependencies:
      'webpack': '*'
  'drizzle-kit@*':
    dependencies:
      'drizzle-orm': '*'
  '@drizzle-team/studio@*':
    dependencies:
      'drizzle-orm': '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry/cli': '*'
  '@socket.io/redis-adapter@*':
    dependencies:
      'socket.io-adapter': '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  react-query@*:
    dependencies:
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.5.1.cjs
