compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@drizzle-team/studio@*':
    dependencies:
      drizzle-orm: '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry/cli': '*'
  '@socket.io/redis-adapter@*':
    dependencies:
      socket.io-adapter: '*'
  '@storybook/nextjs@*':
    dependencies:
      webpack: '*'
  drizzle-kit@*:
    dependencies:
      drizzle-orm: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  postcss-loader@*:
    dependencies:
      autoprefixer: '*'
      tailwindcss: '*'
  react-query@*:
    dependencies:
      react-dom: '*'

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-4.1.0.cjs
