defaultSemverRangePrefix: ''

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@jest/core@*':
    dependencies:
      pretty-format: '*'
  '@sentry/nextjs@*':
    dependencies:
      '@sentry/cli': '*'
  '@tanstack/query-persist-client-core@*':
    dependencies:
      '@tanstack/query-core': '*'
  '@tanstack/react-query-persist-client@*':
    dependencies:
      react: '*'
  '@tanstack/react-query@*':
    dependencies:
      react-dom: '*'
  '@typechain/hardhat@*':
    dependencies:
      lodash: '*'
  '@types/express-winston@*':
    dependencies:
      winston: '*'
  follow-redirects@*:
    dependencies:
      debug: '*'
  handy-redis@*:
    dependencies:
      redis: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  react-dev-utils@*:
    dependencies:
      typescript: '*'
      webpack: '*'
  react-query@*:
    dependencies:
      react-dom: '*'
  react-scripts@*:
    dependencies:
      eslint-plugin-jsdoc: '*'
      eslint-plugin-prefer-arrow: '*'
      eslint-plugin-prettier: '*'
      prettier: '*'
  solidity-coverage@*:
    dependencies:
      hardhat: '*'
  typechain@*:
    dependencies:
      '@typechain/ethers-v5': '*'
  eslint-config-next@*:
    dependencies:
      next: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: 'https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.5.1.cjs
