services:
  app:
    image: 'stellariscloud:latest'
    container_name: stellaris-demo-app
    platform: linux/amd64
    environment:
      APP_HOST_ID: http://stellariscloud.localhost
      INITIAL_USER: 'demo'
      AUTH_JWT_SECRET: 00000000000000000000000000000000
      EMBEDDED_CORE_APP_TOKEN: eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzdGVsbGFyaXNjbG91ZC5sb2NhbGhvc3QiLCJqdGkiOiI5ZWM4MDMxNC1hYmNiLTQzOTItOGE4NC1lYTFjMjE0MWRjNzkiLCJzY3AiOltdLCJzdWIiOiJBUFA6Y29yZSIsImlhdCI6MTczNzkxNzM4NywiZXhwIjoxNzQwNTk1Nzg3fQ.DXX6hMzBgHZlrkM6LY_YCGKGc5WKg5tYJU_xegSZczc-pSze77UmJxgpdymgO6Jdk7ccaORYa2QN5Hyd2fdYpDJTyu5ZlTh6MRgM9Lkm664vRiwc9b3FurIaqmoKiYawk1fQzcpawNibTinlSJ-Fut0QpeEDLgR2suNhxpGRbqoL3Y4PKrrccDyQSm6r5TAPsrGFW2AzLnZFpV85t08pBOkwC9vQ8TGem7z9MNMEQpZkXcd_BAX8LX4_LePTmBbw_2XgEDb-2hd6f7nliVbqkID4MHTbX_pGVZXJVfN7p7-LLcT1jPYIXfLtzf8mZ0dUiAYEdVUiBmOTtp26YGtDDkQd3EJxUwyYunzeR6EsX3_S_ozTGaD-vUl53ANwiM19ZBse5ftqad4MBl1w05ckCrNXlO8ENlI87HVxBWSWTKkv42b6y8A2FSJM8kC6q7QWbfTI_7xF_rJ7ZHq6DYvCSHmDFy_XKfMsI7-OQnhZqznEXCaGTErd-psfFE5_gh1O7WOFovR4Nwl7zKNGiB8hExowyGPGl5kQR4Ez5g9OX-dw2F943kG5w76Hdq9JzjBS2JpDDid2y95lBNFNOZMO_3QLjQtBd4NCFF5_rfgvyvxQbXOPt4cJgYIb09R34eN1t2nx86ym9yZbxH5Mz6ATR_scseCpSGL7OQ_aKh9cqhE
      DB_NAME: stellariscloud_demo
      DB_USER: stellariscloud_demo
      DB_PASSWORD: demodemodemodemodemodemo
      DB_HOST: db
      DB_PORT: 5432
      DISABLE_NOTICE_LOGGING: true
      LOG_LEVEL: debug
      INIT_EVENT_JOBS: true
      INSTALL_APPS_ON_START: true
      CREATE_DATABASE: true
      RUN_MIGRATIONS: true
      APPS_LOCAL_PATH: /usr/src/app/apps
      DISABLE_EMBEDDED_CORE_APP_WORKER: false
    ports:
      - 8090:80

  db:
    image: postgres
    container_name: stellaris-demo-db
    environment:
      POSTGRES_DB: stellariscloud_demo
      POSTGRES_USER: stellariscloud_demo
      POSTGRES_PASSWORD: demodemodemodemodemodemo
    ports:
      - 5438:5432
