services:
  app:
    image: ghcr.io/lombokapp/lombok:latest
    container_name: lombok-demo-app
    environment:
      PLATFORM_HOST: http://lombokdemo.localhost
      INITIAL_USER: demo
      AUTH_JWT_SECRET: 00000000000000000000000000000000 # replace with a random string
      DB_NAME: lombok_demo_db
      DB_USER: lombok_demo_user
      DB_PASSWORD: demodemodemodemodemodemo
      DB_HOST: db
      DB_PORT: 5432
      LOG_LEVEL: debug
      INIT_EVENT_JOBS: true
      INSTALL_APPS_ON_START: true
      CREATE_DATABASE: true
      RUN_MIGRATIONS: true
      APPS_LOCAL_PATH: /usr/src/app/apps
      DISABLE_EMBEDDED_CORE_APP_WORKER: false
      PRINT_EMBEDDED_CORE_APP_WORKER_OUTPUT: true
    ports:
      - 8090:80

  db:
    image: postgres
    container_name: lombok-demo-db
    environment:
      POSTGRES_DB: lombok_demo_db
      POSTGRES_USER: lombok_demo_user
      POSTGRES_PASSWORD: demodemodemodemodemodemo
    ports:
      - 5432:5432