services:
  app:
    image: ghcr.io/stellariscloud/stellariscloud-standalone:latest
    container_name: stellariscloud-standalone-demo-app
    platform: linux/amd64
    environment:
      PLATFORM_HOST: stellarisclouddemo.localhost
      INITIAL_USER: demo
      AUTH_JWT_SECRET: 00000000000000000000000000000000 # replace with a random string
      DB_NAME: stellariscloud_demo
      DB_USER: stellariscloud_demo
      DB_PASSWORD: demodemodemodemodemodemo
      LOG_LEVEL: debug
      INIT_EVENT_JOBS: true
      INSTALL_APPS_ON_START: true
      CREATE_DATABASE: true
      RUN_MIGRATIONS: true
      APPS_LOCAL_PATH: /usr/src/app/apps
      DISABLE_EMBEDDED_CORE_APP_WORKER: false
      PRINT_EMBEDDED_CORE_APP_WORKER_OUTPUT: true
    ports:
      - 8090:80
      - 5432:5432