services:
  app:
    image: 'stellariscloud:latest'
    container_name: stellaris-demo-app
    platform: linux/amd64
    environment:
      APP_HOST_ID: http://stellariscloud.localhost
      INITIAL_USER: 'demo'
      AUTH_JWT_SECRET: 00000000000000000000000000000000
      DB_NAME: stellariscloud_demo
      DB_USER: stellariscloud_demo
      DB_PASSWORD: demodemodemodemodemodemo
      DB_HOST: db
      DB_PORT: 5432
      DISABLE_NOTICE_LOGGING: true
      LOG_LEVEL: debug
      INIT_EVENT_JOBS: true
      INSTALL_APPS_ON_START: true
      CREATE_DATABASE: true
      RUN_MIGRATIONS: true
      APPS_LOCAL_PATH: /usr/src/app/apps
      DISABLE_EMBEDDED_CORE_APP_WORKER: false
    ports:
      - 8090:80

  db:
    image: postgres
    container_name: stellaris-demo-db
    environment:
      POSTGRES_DB: stellariscloud_demo
      POSTGRES_USER: stellariscloud_demo
      POSTGRES_PASSWORD: demodemodemodemodemodemo
    ports:
      - 5438:5432
