services:
  app:
    image: 'stellariscloud:pglatest'
    container_name: stellaris-pg-demo-app
    platform: linux/amd64
    environment:
      APP_HOST_ID: http://stellarisclouddemo.localhost
      INITIAL_USER: 'demo'
      AUTH_JWT_SECRET: 00000000000000000000000000000000
      DB_NAME: stellariscloud_demo
      DB_USER: stellariscloud_demo
      DB_PASSWORD: demodemodemodemodemodemo
      DB_HOST: localhost
      DB_PORT: 5432
      ROOT_DOMAIN: stellarisclouddemo.localhost
      DISABLE_NOTICE_LOGGING: true
      LOG_LEVEL: debug
      INIT_EVENT_JOBS: true
      INSTALL_APPS_ON_START: true
      CREATE_DATABASE: true
      RUN_MIGRATIONS: true
      APPS_LOCAL_PATH: /usr/src/app/apps
      DISABLE_EMBEDDED_CORE_APP_WORKER: false
      PRINT_CORE_PROCESS_WORKER_OUTPUT: true
    ports:
      - 8090:80
