name: lombok-dev

services:
  api:
    container_name: lombok-dev
    build:
      context: .
      dockerfile: docker/app.Dockerfile
      target: dev
    environment:
      - DEV_SEED_FILE=${DEV_SEED_FILE:-default.ts}
      - PLATFORM_HOST=${PLATFORM_HOST:-lombok.localhost}
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_NAME=lombok_dev
      - DB_USER=lombokuser_dev
      - DB_PASSWORD=${DB_PASSWORD:-XXXXXXXX}
      - PLATFORM_HTTPS=false
      - PLATFORM_PORT=3000
      - AUTH_JWT_SECRET=00000000000000000000000000000000
      - AUTH_EMAIL_VERIFICATION_JWT_SECRET=00000000000000000000000000000000
      - LOCAL_DOCKER_SOCKET=${DOCKER_HOST_CONFIG}
      - DOCKER_HOST_CONFIG=${DOCKER_HOST_CONFIG:-{}}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - CREATE_DATABASE=true
      - RUN_MIGRATIONS=true
      - INITIAL_USER=${INITIAL_USER:-dev}
      - DEV_S3_ACCESS_KEY_ID=${DEV_S3_ACCESS_KEY_ID:-lombokdevaccesskey}
      - DEV_S3_SECRET_ACCESS_KEY=${DEV_S3_SECRET_ACCESS_KEY:-lombokdevsecretaccesskey}
      - DEV_S3_BUCKET_NAME=${DEV_S3_BUCKET_NAME:-lombokdevbucket}
      - DEV_S3_PREFIX=${DEV_S3_PREFIX:-dev-local}
      - DEV_S3_REGION=${DEV_S3_REGION:-auto}
      - DEV_S3_ENDPOINT=${DEV_S3_ENDPOINT:-http://127.0.0.1:9000}
      - DEV_S3_LABEL=${DEV_S3_LABEL:-MinioDEV}
      - PRINT_CORE_WORKER_OUTPUT=${PRINT_CORE_WORKER_OUTPUT:-true}
      - PRINT_CORE_WORKER_NSJAIL_VERBOSE_OUTPUT=${PRINT_CORE_WORKER_NSJAIL_VERBOSE_OUTPUT:-true}
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules
      - /usr/src/app/packages/api/node_modules
      - /usr/src/app/packages/app-worker-sdk/node_modules
      - /usr/src/app/packages/auth-utils/node_modules
      - /usr/src/app/packages/core-worker/node_modules
      - /usr/src/app/packages/worker-utils/node_modules
      - /usr/src/app/packages/sdk/node_modules
      - /usr/src/app/packages/types/node_modules
      - /usr/src/app/packages/utils/node_modules
      - /usr/src/app/packages/ui/node_modules
      - /usr/src/app/packages/ui-toolkit/node_modules
      - /usr/src/app/packages/app-demo
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PGDATA_DIR:-pgdata}:/var/lib/postgresql/data
      - ${MINIO_DATA_DIR:-miniodata}:/var/lib/minio/data
    ports:
      - 3000:3000
      - 5432:${HOST_DB_PORT:-5432}
      - 5173:5173
      - 9000:9000
      - 9001:9001
    cap_drop: [ALL]
    cap_add:
      - SETUID
      - SETGID
      - SYS_ADMIN
      - SYS_CHROOT
      - SETPCAP
      - CHOWN
    security_opt:
      - seccomp=unconfined
      - no-new-privileges:false
      - apparmor=unconfined
    userns_mode: host

volumes:
  pgdata:
  miniodata:
