export enum DocumentMediaMimeTypes {
  TXT = 'text/plain',
  PDF = 'application/pdf',
  EPUB = 'application/epub+zip',
  JSON = 'application/json',
  CSV = 'text/csv',
  TSV = 'text/tab-separated-values',
  MPD = 'application/dash+xml',
  M3U8 = 'application/vnd.apple.mpegurl',
  XLS = 'application/vnd.ms-excel',
  XML = 'application/xml',
  XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  HTML = 'text/html',
  DOC = 'application/msword',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
}
