package cmd

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"time"

	"lombok-worker-agent/internal/config"
	"lombok-worker-agent/internal/logs"

	"github.com/spf13/cobra"
)

const (
	provisionPollInterval = 250 * time.Millisecond
	provisionTimeout      = 10 * time.Second
)

var provisionCmd = &cobra.Command{
	Use:   "provision",
	Short: "Provision container with platform credentials (called by the platform after start)",
	Long: `Accepts key=value environment variables and persists them inside the container.
The platform execs this command after 'start' to inject credentials such as container
tokens. Requires the one-time secret generated by 'start'.`,
	RunE: provision,
}

var provisionSecret string

func init() {
	provisionCmd.Flags().StringVar(&provisionSecret, "secret", "", "One-time secret generated by the start command (required)")
	_ = provisionCmd.MarkFlagRequired("secret")
}

func provision(cmd *cobra.Command, args []string) error {
	// If the provision.env file already exists and the secret file is gone,
	// provisioning was already completed — bail with success.
	if _, err := os.Stat(config.ProvisionEnvPath()); err == nil {
		if _, err := os.Stat(config.ProvisionSecretPath()); errors.Is(err, os.ErrNotExist) {
			fmt.Fprintln(os.Stdout, "already provisioned, skipping")
			return nil
		}
	}

	// Wait for the provision-secret file to appear (the 'start' entrypoint
	// writes it during initialisation and may not have finished yet).
	deadline := time.Now().Add(provisionTimeout)
	var storedSecret []byte
	for {
		data, err := os.ReadFile(config.ProvisionSecretPath())
		if err == nil {
			storedSecret = data
			break
		}
		if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("failed to read provision secret: %w", err)
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("timed out waiting for provision secret (has 'start' been run?)")
		}
		time.Sleep(provisionPollInterval)
	}

	// Verify the secret
	if strings.TrimSpace(string(storedSecret)) != provisionSecret {
		return fmt.Errorf("invalid secret")
	}

	// Parse key=value pairs from args
	if len(args) == 0 {
		return fmt.Errorf("at least one KEY=VALUE argument is required")
	}

	var envLines []string
	for _, arg := range args {
		parts := strings.SplitN(arg, "=", 2)
		if len(parts) != 2 || parts[0] == "" {
			return fmt.Errorf("invalid argument %q: expected KEY=VALUE", arg)
		}
		envLines = append(envLines, arg)
	}

	// Write the env file
	content := strings.Join(envLines, "\n") + "\n"
	if err := os.WriteFile(config.ProvisionEnvPath(), []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write provision env file: %w", err)
	}

	// Delete the secret file — one-time use
	_ = os.Remove(config.ProvisionSecretPath())

	logs.WriteAgentLog(logs.LogLevelInfo, "Container provisioned", map[string]any{
		"keys_count": len(envLines),
	})

	fmt.Fprintf(os.Stdout, "set %d provision variable(s)\n", len(envLines))
	return nil
}
