package cmd

import (
	"errors"
	"fmt"
	"os"
	"strings"
	"syscall"
	"time"

	"lombok-worker-agent/internal/config"
	"lombok-worker-agent/internal/logs"

	"github.com/spf13/cobra"
)

const (
	provisionPollInterval = 250 * time.Millisecond
	provisionTimeout      = 10 * time.Second
)

var provisionCmd = &cobra.Command{
	Use:   "provision",
	Short: "Provision container with platform credentials (called by the platform after start)",
	Long: `Accepts key=value environment variables and persists them inside the container.
The platform execs this command after 'start' to inject credentials such as container
tokens. Requires the one-time secret generated by 'start'.`,
	RunE: provision,
}

var (
	provisionSecret  string
	provisionChownPaths string
)

func init() {
	provisionCmd.Flags().StringVar(&provisionSecret, "secret", "", "One-time secret generated by the start command (required)")
	provisionCmd.Flags().StringVar(&provisionChownPaths, "chown-paths", "", "Comma-separated container paths to chown to the container's default user")
	_ = provisionCmd.MarkFlagRequired("secret")
}

func provision(cmd *cobra.Command, args []string) error {
	// If the provision.env file already exists and the secret file is gone,
	// provisioning was already completed — bail with success.
	if _, err := os.Stat(config.ProvisionEnvPath()); err == nil {
		if _, err := os.Stat(config.ProvisionSecretPath()); errors.Is(err, os.ErrNotExist) {
			fmt.Fprintln(os.Stdout, "already provisioned, skipping")
			return nil
		}
	}

	// Wait for the provision-secret file to appear (the 'start' entrypoint
	// writes it during initialisation and may not have finished yet).
	deadline := time.Now().Add(provisionTimeout)
	var storedSecret []byte
	for {
		data, err := os.ReadFile(config.ProvisionSecretPath())
		if err == nil {
			storedSecret = data
			break
		}
		if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("failed to read provision secret: %w", err)
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("timed out waiting for provision secret (has 'start' been run?)")
		}
		time.Sleep(provisionPollInterval)
	}

	// Verify the secret
	if strings.TrimSpace(string(storedSecret)) != provisionSecret {
		return fmt.Errorf("invalid secret")
	}

	// Parse key=value pairs from args
	if len(args) == 0 {
		return fmt.Errorf("at least one KEY=VALUE argument is required")
	}

	var envLines []string
	for _, arg := range args {
		parts := strings.SplitN(arg, "=", 2)
		if len(parts) != 2 || parts[0] == "" {
			return fmt.Errorf("invalid argument %q: expected KEY=VALUE", arg)
		}
		envLines = append(envLines, arg)
	}

	// Write the env file
	content := strings.Join(envLines, "\n") + "\n"
	if err := os.WriteFile(config.ProvisionEnvPath(), []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write provision env file: %w", err)
	}

	// Delete the secret file — one-time use
	_ = os.Remove(config.ProvisionSecretPath())

	// Chown the env file (and optional volume mount points) to the container's
	// default user. The default user is determined by inspecting PID 1's ownership
	// (the main entrypoint process started by Docker with the image's USER directive).
	// This is necessary because provision may run as root while the main process
	// runs as a non-root user.
	uid, gid, err := getContainerDefaultOwner()
	if err != nil {
		return fmt.Errorf("failed to detect container default user: %w", err)
	}

	if err := os.Chown(config.ProvisionEnvPath(), uid, gid); err != nil {
		return fmt.Errorf("failed to chown provision env file: %w", err)
	}

	if provisionChownPaths != "" {
		for _, p := range strings.Split(provisionChownPaths, ",") {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			if err := os.Chown(p, uid, gid); err != nil {
				return fmt.Errorf("failed to chown %s: %w", p, err)
			}
			logs.WriteAgentLog(logs.LogLevelInfo, "Chowned volume mount", map[string]any{
				"path": p,
				"uid":  uid,
				"gid":  gid,
			})
		}
	}

	logs.WriteAgentLog(logs.LogLevelInfo, "Container provisioned", map[string]any{
		"keys_count": len(envLines),
	})

	fmt.Fprintf(os.Stdout, "set %d provision variable(s)\n", len(envLines))
	return nil
}

// getContainerDefaultOwner returns the uid/gid of PID 1, which reflects the
// USER directive from the container image.
func getContainerDefaultOwner() (int, int, error) {
	info, err := os.Stat("/proc/1")
	if err != nil {
		return 0, 0, fmt.Errorf("failed to stat /proc/1: %w", err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		return 0, 0, fmt.Errorf("failed to get syscall.Stat_t from /proc/1")
	}
	return int(stat.Uid), int(stat.Gid), nil
}
