package cmd

import (
	"fmt"
	"os"
	"strings"

	"lombok-worker-agent/internal/config"
	"lombok-worker-agent/internal/logs"

	"github.com/spf13/cobra"
)

var setContextCmd = &cobra.Command{
	Use:   "set-context",
	Short: "Set container context variables (called by the platform after start)",
	Long: `Accepts key=value environment variables and persists them inside the container.
The platform execs this command after 'start' to inject context such as container ID
and authentication tokens. Requires the one-time secret generated by 'start'.`,
	RunE: setContext,
}

var setContextSecret string

func init() {
	setContextCmd.Flags().StringVar(&setContextSecret, "secret", "", "One-time secret generated by the start command (required)")
	_ = setContextCmd.MarkFlagRequired("secret")
}

func setContext(cmd *cobra.Command, args []string) error {
	// 1. Read and verify the secret
	storedSecret, err := os.ReadFile(config.ContextSecretPath())
	if err != nil {
		return fmt.Errorf("failed to read context secret (has 'start' been run?): %w", err)
	}

	if strings.TrimSpace(string(storedSecret)) != setContextSecret {
		return fmt.Errorf("invalid secret")
	}

	// 2. Parse key=value pairs from args
	if len(args) == 0 {
		return fmt.Errorf("at least one KEY=VALUE argument is required")
	}

	var envLines []string
	for _, arg := range args {
		parts := strings.SplitN(arg, "=", 2)
		if len(parts) != 2 || parts[0] == "" {
			return fmt.Errorf("invalid argument %q: expected KEY=VALUE", arg)
		}
		envLines = append(envLines, arg)
	}

	// 3. Write the env file
	content := strings.Join(envLines, "\n") + "\n"
	if err := os.WriteFile(config.ContextEnvPath(), []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write context env file: %w", err)
	}

	// 4. Delete the secret file — one-time use
	_ = os.Remove(config.ContextSecretPath())

	logs.WriteAgentLog(logs.LogLevelInfo, "Container context set", map[string]any{
		"keys_count": len(envLines),
	})

	fmt.Fprintf(os.Stdout, "set %d context variable(s)\n", len(envLines))
	return nil
}
