import type { ContainerConfigState } from './container-config.types'

export const EMPTY_CONFIG_STATE: ContainerConfigState = {
  mounts: '',
  tmpfs: '',
  devices: '',
  env: '',
  ports: [],
  networkMode: '',
  extraHosts: '',
  hostname: '',
  domainName: '',
  dns: '',
  dnsSearch: '',
  memoryLimit: '',
  cpuShares: '',
  cpuQuota: '',
  pidsLimit: '',
  shmSize: '',
  gpuDeviceIds: '',
  entrypoint: '',
  command: '',
  workingDir: '',
  user: '',
  stopSignal: '',
  stopTimeout: '',
  restartPolicy: 'none',
  privileged: false,
  readOnly: false,
  capAdd: '',
  capDrop: '',
  securityOpt: '',
  ipcMode: '',
  pidMode: '',
  cgroupParent: '',
  runtime: '',
  labels: '',
  ulimits: '',
  sysctls: '',
}
