name: API E2E Tests

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build-image:
    uses: ./.github/workflows/build-e2e-image.yml
    permissions:
      contents: read
      packages: write

  test:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Run API E2E tests
        run: docker run --rm --privileged ${{ needs.build-image.outputs.image }} -- api
