name: Unit Tests

on:
  push:
    branches:
      - '**' # matches every branch
      - '!main' # excludes master
  workflow_dispatch:

jobs:
  check-api:
    name: Check @lombokapp/api package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9
      - run: bun install
      - run: bun --cwd packages/api test:unit

  check-app-worker-sdk:
    name: Check @lombokapp/app-worker-sdk package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9
      - run: bun install
      - run: bun --cwd packages/app-worker-sdk test:unit

  # check-auth-utils:
  #   name: Check @lombokapp/auth-utils package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: 1.3.9
  #     - run: bun install
  #     - run: bun --cwd packages/auth-utils test:unit

  # check-core-worker:
  #   name: Check @lombokapp/core-worker package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: 1.3.9
  #     - run: bun install
  #     - run: bun --cwd packages/core-worker test:unit

  # check-sdk:
  #   name: Check @lombokapp/sdk package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: 1.3.9
  #     - run: bun install
  #     - run: bun --cwd packages/sdk test:unit

  check-lombok-types:
    name: Check @lombokapp/types package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9
      - run: bun install
      - run: bun --cwd packages/types test:unit

  check-utils:
    name: Check @lombokapp/utils package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.9
      - run: bun install
      - run: bun --cwd packages/utils test:unit

  # check-worker-utils:
  #   name: Check @lombokapp/worker-utils package
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: 1.3.9
  #     - run: bun install
  #     - run: bun --cwd packages/worker-utils test:unit
